### ISSUE TITLE
RFE, include example for supply chain mgmt

### ISSUE THREAD

**Issue by kim0** [eomahony/Numberjack#21]
It would be great to include an example of a process that varies with time. i.e. the solution is not a single state, but rather a time varying state. One such example is a supply chain management problem, where every day some raw-material is bought, stored into warehouse, and some raw material goes into the factory for production, resulting products are sold. How to optimize overall cost, while maintaining certain thresholds (min raw material in warehouse, min cash in bank) ..etc as a time variant process

**Comment by 9thbit** [comment]
Hi @kim0, thanks for the request. You may be interested in reading problem 047 on CSPlib: http://www.csplib.org/Problems/prob047/

Barry
