### ISSUE TITLE
Mistral2 with parallel support

### ISSUE THREAD

**Issue by braingineer** [eomahony/Numberjack#28]
Hello!  

I noticed that Mistral 2 now has parallelism/multicore support.  How would I go about using this feature from Numberjack?

Thanks,
Brian

**Comment by 9thbit** [comment]
Hi Brian,
I've asked the developers of Mistral 2, and they say that the search is not parallelised, the -p option simply starts multiple versions of the solver with different parameterisations and returns the best solution. At the moment, this would be non-trivial to build into Numberjack itself but it has already been implemented on top. Take a look at the script https://github.com/eomahony/Numberjack/blob/master/fzn/njportfolio.py which can be used to launch multiple solvers on any Numberjack model and returns the best solution within the time limit.

Regards,
Barry

**Comment by braingineer** [comment]
Hi Barry,

Aah. Ok. Thanks for checking into this!

Best,
Brian
