### ISSUE TITLE
Confused about constraints

### ISSUE THREAD

**Issue by braingineer** [eomahony/Numberjack#31]
Hello,

I am trying to build a model that mimics [topological dependency parsing](http://www.aclweb.org/anthology/P02-1003).  In short, I have multiple lexicon entries for a word, where each entry is a tree fragment and has a different structure.  The model is to pick one lexicon entry for each word that can combines with the rest of the entries to form 1 structure.  

For the constraints, I have created a unique binary Variable for each lexicon entry.  I then set a constraint for the Sum over the variables to be 1.   So, given other constraints, only 1 of the lexicon entries for each word can be active.  

However, I seem to be having some issues with this.   At the current moment, the solver is spitting back results, but it's clearly violating constraints.  For example, Because there is only one option for the word "motorbike", that option must be selected.  But, the constraint that sets the motorbike variable to 1 has a value of 0 in the solution set.  So, if I do:

```python
for constraint in model.constraints:
    print("{}: {}".format(constraint.get_value(), str(constraint)))
```

one of the printed results is 

`0:(motorbike-g8-1608 == 1)` 

(I have named my variables to be [word]-[logical_variable]-[unique_tree_id])

I thought in defining a set of constraints, it is supposed to find an assignment to the Variables that make all constraints True.  If this isn't true, then I think my problem means I am misunderstanding how things are set up. Is it that the solver can set values to my constraints and use that as a solution mechanism?

It's hard to share the code because it's a part of a larger research project and requires a bunch of infrastructure and data to make work.  

The set of constraints that I'm using though are:

```python
    @staticmethod
    def align_root_constraints(ident_var, root_edge_vars):
        return (((ident_var == 1) & (Numberjack.Sum(root_edge_vars) == 1)) |
                ((ident_var == 0) & (Numberjack.Sum(root_edge_vars) == 0)))

    @staticmethod
    def align_sub_point_constraints(ident_var, point_edge_vars):
        return (((ident_var == 1) & (Numberjack.Sum(point_edge_vars) == 1)) |
                ((ident_var == 0) & (Numberjack.Sum(point_edge_vars) == 0)))

    @staticmethod
    def align_ins_point_constraints(ident_var, point_edge_vars):
        return (((ident_var == 1) & (Numberjack.Sum(point_edge_vars) >= 0)) |
                ((ident_var == 0) & (Numberjack.Sum(point_edge_vars) == 0)))

    @staticmethod
    def unique_constraint(symlist):
        return (Numberjack.Sum(symlist) == 1)

```

Here, the ident_var is for a lexicon entry.  I am using it to force only 1 lexicon entry to be active in solution, and to force all types of attachments to agree on this. 

Thanks for your time,
Brian

**Comment by 9thbit** [comment]
Hi Brian,
In the example you sent, you are printing the value of the constraint, not the variable. So you should be keeping track of the decision variables and getting their .get_value() instead, not the constraints.

Also, in some of the constraint examples you sent, you can simplify them by to simply: `Sum(...) == ident_var`.

Regards,
Barry

**Comment by braingineer** [comment]
Hi Barry,

Thanks for your response.  I was running through all possible reasons why things could be going wrong.  Your answer provided some definite evidence that helped.  

I couldn't tell if there was a bad assumption coming from my end about how the constraints were being handled.  I had also thought that after a model ran, some of the constraints were maybe false.   (I was wrong, of course)

re: the shortcut.  Oh! That is a good simplification, thank you.  

Thanks again, 
All the best,
Brian
