### ISSUE TITLE
Toulbar2 cannot be loaded

### ISSUE THREAD

**Issue by Alexander-Schiendorfer** [eomahony/Numberjack#32]
I tried to install and run Numberjack on a freshly installed Ubuntu 15.10.

I get the following error message 

```
/home/alexander/anaconda2/lib/python2.7/site-packages/_Toulbar2.so: undefined symbol: 
_ZN16BinaryConstraint10projectionI15Functor_getCostEEvT_P18EnumeratedVariableS4_iRSt6vectorI10StoreBasicIxESaIS7_EE
```
from printing the exception in __init__.py

```
except ImportError as e:			
            print e
            raise ImportError(
                "ERROR: Failed during import, wrong module name? (%s)" %
                solvername)
```

Toulbar2 is also installed on my system but it can't be loaded with Numberjack, other solvers (Mistral2) are fine.

Cheers,
Alex

**Comment by Alexander-Schiendorfer** [comment]
I could resolve the issue with an updated _Toulbar2.so from an older installation but that should only be a hack... maybe this issue is known?

**Comment by Alexander-Schiendorfer** [comment]
I can give some more hints; it has to do with the gcc version used. With 4.8.5, the error is not present, with 5.2.1, the error shows up.

**Comment by 9thbit** [comment]
Hi @Alexander-Schiendorfer, the Toulbar2 developers tell me this is to do with the version not being compilable under the newest g++ v5.2. They'll push a newer version to the repo soon though which will hopefully resolve this.

**Comment by Alexander-Schiendorfer** [comment]
I have just tried compiling Toulbar2 with g++ 5.2 -- works like a charm!
