### ISSUE TITLE
Explicit Timeout detection

### ISSUE THREAD

**Issue by jbum** [eomahony/Numberjack#39]
I'm currently using Numberjack for puzzle solving / generation.  I'm working on a Hidato generator, and sometimes accidentally generate candidate puzzles which are pathological hard to solve.  I'd like to skip these using setTimeout().

When I use Mistral, solver.getNextSolution() returns 4 when a timeout occurs (via setTimeLimit).  I don't see a documented constant that corresponds to this, nor a function for detecting that a timeout occurred, so I'm currently using the magic number 4 to detect it.  It would be good to have explicit support for detecting timeouts.

Here is a sample solver for square-grid Hidato puzzles that includes a particularly hard puzzle that generates a timeout, for testing purposes.

https://gist.github.com/jbum/7773f18ad8d99333ce1b4ce8b4220e91

https://en.wikipedia.org/wiki/Hidato

**Comment by 9thbit** [comment]
Hi @jbum, thanks for your bug report. The 4 was actually supposed to be `LIMITOUT` but it was incorrectly set to 3 in `Numberjack/__init__.py`. I've pushed a change to master with it set to 4 now.

**Comment by jbum** [comment]
Awesome thanks!
