### ISSUE TITLE
Segfault using Table constraint

### ISSUE THREAD

**Issue by jbum** [eomahony/Numberjack#40]
I'm currently using Numberjack for puzzle solving / generation. I'm working on a Hidato puzzle generator, and sometimes accidentally generate candidate puzzles which segfault.

Here is sample code for a Hidato solver. The first puzzle in the list generates a segfault.  If I remove the Table constraints, the segfault doesn't happen.  The other puzzles seem to be fine.

https://gist.github.com/jbum/f40c15f6f8d2689f4fe5575b28250ee4

Here's the error log / stacktrace:

[segfault_errordump.txt](https://github.com/eomahony/Numberjack/files/275575/segfault_errordump.txt)

**Comment by jbum** [comment]
Interestingly, you can add one additional clue to the segfaulting puzzle to fix it....

  ```
( # does NOT cause segfault (has 1 valid solution)
    (7,7),
    (24, 23, 0, 21, 0, 0, 18, 
     0, 44, 43, 42, 41, 17, 0, 
     45, 0, 0, 0, 39, 15, 0, 
     0, 28, 0, 38, 37, 13, 0, 
     0, 30, 31, 0, 0, 11, 10, 
     48, 0, 35, 5, 0, 7, 0, 
     49, 0, 34, 0, 4, 1, 0)
  ),

```

**Comment by 9thbit** [comment]
Hi @jbum, thanks for the bug report. I believe this is a bug in the solver Mistral. We plan to deprecate this solver as the successor version Mistral2 is being actively maintained but the original version 1 is no longer. But I don't think Mistral2 has support for Table constraints so I will have to check with the developers for that. But for now you should be able to solve this problem with one of the SAT solvers, like `MiniSat`, just change `Mistral` to `MiniSat` in your code and it should work. Let us know if you have any other issues.

Once you have your Hidato example complete, it would be great if you would consider submitting a pull-request to add it to the set of examples. :)

**Comment by jbum** [comment]
Cool thanks.  I'll have a handful of new puzzle examples for you soon.

**Comment by jbum** [comment]
I tried running this code with MiniSat.  

python hidatoTest.py -solver MiniSat

And it has a problem with the method I'm using to produce the answer string.  When I use MiniSat, my variables evaluate to None instead of an integer, after the first solution.

```
$ python hidatoTest.py -solver MiniSat
example 1:
Traceback (most recent call last):
  File "hidatoTest.py", line 113, in <module>
    print "example %d:" % (n+1),solve(param, puzz)
  File "hidatoTest.py", line 55, in solve
    answer[ positions[i].get_value() ] = i+1
TypeError: list indices must be integers, not NoneType
```

Is there a trick to pulling answers from MiniSat?

**Comment by 9thbit** [comment]
No tricks. None values likely mean that a solution wasn't found. Can you replace the following two lines:
```
solver.startNewSearch()
res = solver.getNextSolution()
```
with
```
res = solver.solve()
```

The first two lines are for when you want to find multiple or all solutions to a model. I'm not sure why that's not working for you but I'll investigate when I get a chance. But it looks like you're just trying to find one solution, so you can just use the second option. This gives me solutions using your sample code. :)

**Comment by jbum** [comment]
Okay cool!  When using NumberJack for puzzle construction.  I need to be
able to stop at the 2nd solution (to avoid wasted work), rather than
generating all possible solutions.  I was under the impression that solve()
generated all solutions...  If there's a more efficient way to stop at 2,
let me know.
