### ISSUE TITLE
Support Gurobi Compute Server running in the cloud

### ISSUE THREAD

**Issue by shankari** [eomahony/Numberjack#41]
Gurobi now has a compute server option in which a gurobi server can be provisioned on a cloud platform such as AWS and connected to using a client, which could be a laptop or any other server. It doesn't look like Numberjack supports such a configuration since it expects Gurobi to be installed on the same server as numberjack.
http://www.gurobi.com/documentation/6.5/cloud-guide/aws/configurations.html

Is there a chance that this can be addressed?

**Comment by 9thbit** [comment]
Hi, we do not plan to add support for this but maybe you can fork the code and try for yourself. We would welcome this as pull request.

Regards,
Barry
