### ISSUE TITLE
Get only the first solution

### ISSUE THREAD

**Issue by Abraxos** [eomahony/Numberjack#44]
Hello,

I admit that perhaps this is more suited to a forum, but I'm unable to figure out how to instruct the solver to only get the first solution. I do not care about all possible solution, only the first one that can be found. Could you please point me to an example that demonstrates how to do this?

Thank you.

**Comment by 9thbit** [comment]
Hi @Abraxos, if you look in the `examples` folder, there are numerous example of finding a single solution, such as `NQueens.py`. You just call `solver.solve()`. There are only a handful of cases for finding the optimal or for finding all solutions.

**Comment by Abraxos** [comment]
Thanks for getting back to me.

It may be that I am making a mistake somewhere, but it seems like when I call `solver.solve()` on a Mistral solver it actually produces all possible solutions?

Right now what I have is something like this:

```
# Variables and constraints defined here
# Solve the model                                                                                       
solver = model.load('Mistral')                                                                          
solver.setHeuristic('MinDomainMinVal', 'Lex')                                                           
solver.setTimeLimit(30)                                                                                 
solver.solve()                                                                                          
                                                                                                        
if solver.is_sat():                                                                                     
    for sol in solver.solutions():
        # print the results
```

What I am going for is that I want the solver to find the first solution and then stop solving, but the result is that I seem to get all possible solutions which means that the `solver.solve()` seems to take a while. Is there anything inherently wrong with what I am doing that may signal why I am getting all possible solutions?

**Comment by 9thbit** [comment]
The `solver.solve()` is where it finds the first solutions, when you loop over `solver.solutions()` you're asking for more solutions, just remove this and print the `variable.get_value()` inside the `if solver.is_sat()`.

Take a look at the examples for how they are doing it, most of them are just finding a single solution.

**Comment by Abraxos** [comment]
Aha, so the solutions() function is a generator? and it prompts the solver to generate new solutions? That makes sense. Thanks!
